### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by raphaeldealmeida** [yajra/laravel-datatables-docs#60]
Website https://yajrabox.com/docs/laravel-datatables is offline

**Comment by jufianto** [comment]
same here

**Comment by RishabSwift** [comment]
Here you are:

[Docs](https://laravel-datatables-docs.netlify.com/) provided by @bm2ilabs

**Comment by iwane021** [comment]
I also get offline the website,

**Comment by Dictator1999** [comment]
oooofs. Once again

**Comment by yajra** [comment]
Yes, please use this repo atm for the docs. Will bring the server up after I received my first pay check for this year. 

Donations is appreciated though 😃 .
