### ISSUE TITLE
When I put the editor code it doesn't work

### ISSUE THREAD

**Issue by markplus** [yajra/laravel-datatables-docs#94]
I bought the editor, but if I follow your guide, when I insert the editor buttons everything disappears, it doesn't work and I don't understand why, I'm using laravel 10 and I followed all the guide described here but when I put the editor I can't see anything anymore
it stays loading and you don't see any buttons

[![Screenshot-2023-08-01-094933.png](https://i.postimg.cc/RhJVXkMN/Screenshot-2023-08-01-094933.png)](https://postimg.cc/V018NH08)

**Comment by yajra** [comment]
You might be missing the `B` on your `dom` for buttons. Any console error logs?

**Comment by markplus** [comment]
> You might be missing the `B` on your `dom` for buttons. Any console error logs?
Sorry yes, due to distraction I forgot
